
project:
  type: website

website:
  title: "Jinju Suk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: Jinju_Suk.pdf
        text: Curriculum Vitae  
      - text: 24FALL_Assignments
        menu: 
         - href: 24assignments1.qmd
           text: Assignment 1
      - text: Assignments
        menu: 
          - href: assignments1.qmd
            text: Assignment 1
          - href: assignments2.qmd
            text: Assignment 2
          - href: assignments3.qmd
            text: Assignment 3
          - href: assignments4.qmd
            text: Assignment 4
          - href: assignments5.qmd
            text: Assignment 5 
          - href: assignments6.qmd
            text: Assignment 6 
          - href: assignments7.qmd
            text: Assignment 7
          - href: assignments8.qmd
            text: Assignment 8
          - href: Lab01.qmd
            text: Lab 01
          - href: Lab02.qmd
            text: Lab 02
          - href: Lab03.qmd
            text: Lab 03
          - href: Lab04.qmd
            text: Lab 04
          - href: Lab05.qmd
            text: Lab_linearregression
         
       

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual
