project: 
  type: website

website:
  title: "Jinju Suk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: Jinju_Suk.pdf
        text: Curriculum Vitae  
      - text: Assignments
        menu: 
          - href: assignment1.qmd
            text: assignment1
          - href: assignments2.qmd
            text: assignment2
          - href: assignment3.qmd
            text: assignment3
          - href: Lab01.qmd
            text: Lab01
          - href: Lab02.qmd
            text: Lab02



format:
  html:
    theme: Minty
    css: styles.css
    toc: true
  



editor: visual
